// Auto-generated by LibreLane
module andig_clock(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input in_clk,
  input rst,
  output out_clk1,
  output out_clk2,
  output out_clk2B,
  output out_clk_cic
);
endmodule
