// Auto-generated by LibreLane
module piso_12bit(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input load_en,
  input[11:0] data_in,
  output serial_out
);
endmodule
